substitutions:
  devicename: atomlite-distance
esphome:
  name: atomlite-distance
  name_add_mac_suffix: true
  platformio_options:
    build_flags:
      - -D CORE_DEBUG_LEVEL=0
      - -D ARDUINO_LOG_LEVEL=0
  min_version: 2026.7.3
  build_path: build/atomlite-distance
  friendly_name: ''
  build_flags: []
  environment_variables: {}
  includes: []
  includes_c: []
  libraries: []
  merge_warnings: true
  debug_scheduler: false
  areas: []
  devices: []
esp32:
  board: m5stack-atom
  framework:
    type: arduino
    version: 3.3.10
    sdkconfig_options: {}
    log_level: ERROR
    advanced:
      compiler_optimization: SIZE
      enable_idf_experimental_features: false
      enable_lwip_assert: true
      ignore_efuse_custom_mac: false
      ignore_efuse_mac_crc: false
      sram1_as_iram: false
      enable_lwip_mdns_queries: true
      enable_lwip_bridge_interface: false
      enable_lwip_tcpip_core_locking: true
      enable_lwip_check_thread_safety: true
      disable_libc_locks_in_iram: true
      disable_vfs_support_termios: true
      disable_vfs_support_select: true
      disable_vfs_support_dir: true
      freertos_in_iram: false
      ringbuf_in_iram: false
      heap_in_iram: false
      execute_from_psram: false
      loop_task_stack_size: 8192
      enable_ota_rollback: true
      enable_ota_downgrade_protection: false
      use_full_certificate_bundle: false
      include_builtin_idf_components: []
      enable_full_printf: false
      disable_debug_stubs: true
      disable_ocd_aware: true
      disable_usb_serial_jtag_secondary: true
      disable_dev_null_vfs: true
      disable_mbedtls_peer_cert: true
      disable_mbedtls_pkcs7: true
      disable_regi2c_in_iram: true
      adc_oneshot_in_iram: false
      disable_fatfs: true
    components: []
  flash_size: 4MB
  watchdog_timeout: 5s
  variant: ESP32
  cpu_frequency: 240MHZ
uart:
  - id: uart_bus
    rx_pin:
      number: 22
      mode:
        input: true
        output: false
        open_drain: false
        pullup: false
        pulldown: false
      id: esp32_esp32internalgpiopin_id
      inverted: false
      ignore_pin_validation_error: false
      ignore_strapping_warning: false
      drive_strength: 20.0
    tx_pin:
      number: 19
      mode:
        output: true
        input: false
        open_drain: false
        pullup: false
        pulldown: false
      id: esp32_esp32internalgpiopin_id_2
      inverted: false
      ignore_pin_validation_error: false
      ignore_strapping_warning: false
      drive_strength: 20.0
    baud_rate: 115200
    rx_buffer_size: 256
    rx_timeout: 2
    stop_bits: 1
    data_bits: 8
    parity: NONE
modbus:
  - id: modbus_bus
    uart_id: uart_bus
    send_wait_time: 2000ms
    turnaround_time: 600ms
    role: client
modbus_controller:
  - id: sen0592
    modbus_id: modbus_bus
    address: 0x01
    setup_priority: -10.0
    allow_duplicate_commands: false
    command_throttle: 0ms
    max_cmd_retries: 4
    offline_skip_updates: 0
    update_interval: 60s
sensor:
  - platform: modbus_controller
    modbus_controller_id: sen0592
    id: distance_mm
    name: SEN0592 Distance
    register_type: holding
    address: 256
    value_type: U_WORD
    unit_of_measurement: mm
    accuracy_decimals: 0
    disabled_by_default: false
    force_update: false
    bitmask: 0xFFFFFFFF
    skip_updates: 0
    force_new_range: false
    response_size: 0
    register_count: 0
wifi:
  reboot_timeout: 15min
  output_power: 15.0
  power_save_mode: NONE
  ap:
    id: wifi_wifiap_id
    ap_timeout: 90s
  id: wifi_wificomponent_id
  domain: .local
  fast_connect:
    enabled: false
    storage: flash
  enable_btm: false
  enable_rrm: false
  passive_scan: false
  enable_on_boot: true
  post_connect_roaming: true
  min_auth_mode: WPA2
  use_address: atomlite-distance.local
captive_portal:
  id: captive_portal_captiveportal_id
  web_server_base_id: web_server_base_webserverbase_id
  compression: gzip
improv_serial:
  id: improv_serial_improvserialcomponent_id
logger:
  level: DEBUG
  logs:
    sensor: WARN
    text_sensor: WARN
  id: logger_logger_id
  baud_rate: 115200
  tx_buffer_size: 512
  deassert_rts_dtr: false
  task_log_buffer_size: 768
  hardware_uart: UART0
  runtime_tag_levels: false
api:
  reboot_timeout: 0s
  id: api_apiserver_id
  port: 6053
  batch_delay: 100ms
  custom_services: false
  homeassistant_services: false
  homeassistant_states: false
  listen_backlog: 4
  max_connections: 5
  max_send_queue: 8
ota:
  - platform: web_server
    id: web_server_webserverotacomponent_id
  - platform: esphome
    id: esphome_esphomeotacomponent_id
    version: 2
    port: 3232
    allow_partition_access: false
web_server:
  include_internal: false
  version: 3
  id: web_server_webserver_id
  port: 80
  enable_private_network_access: false
  web_server_base_id: web_server_base_webserverbase_id
  log: true
  compression: gzip
  css_url: ''
  js_url: https://oi.esphome.io/v3/www.js
preferences:
  id: preferences_intervalsyncer_id
  flash_write_interval: 60s
network:
  id: network_networkcomponent_id
  enable_ipv6: false
  min_ipv6_addr_count: 0
web_server_base:
  id: web_server_base_webserverbase_id
socket:
  implementation: bsd_sockets
improv_base: {}
safe_mode:
  id: safe_mode_safemodecomponent_id
  boot_is_good_after: 1min
  disabled: false
  num_attempts: 10
  reboot_timeout: 5min
  storage: flash
md5: {}
watchdog: {}
sha256: {}
json: {}
mdns:
  id: mdns_mdnscomponent_id
  disabled: false
  services: []
web_server_idf: {}
